### admin-inquiry-veiw-test
GET http://localhost:8001/admin/inquiry
Access-Token: eyJkYXRlIjoxNzE3MDQzMjAzMTg5LCJ0eXBlIjoiand0IiwiYWxnIjoiSFM1MTIifQ.eyJtZW1iZXJSb2xlIjoiUk9MRV9BRE1JTiIsIm1lbWJlcklkIjoidXNlcjAyIiwiZXhwIjoxNzE3MDQ2ODAzfQ.7RgKlyw-armu8E-8si9vh8KdLmducbWYDuclXF2XpWqhUJaKVMV1ox1oil3uC79vgNNhAPE0wBPqeZvJwL19HQ

###admin-inquiry-regist-test
GET http://localhost:8001/admin/inquiry/regist
Access-Token: eyJkYXRlIjoxNzE3MDQ4NTIyNzkwLCJ0eXBlIjoiand0IiwiYWxnIjoiSFM1MTIifQ.eyJtZW1iZXJSb2xlIjoiUk9MRV9BRE1JTiIsIm1lbWJlcklkIjoidXNlcjAyIiwiZXhwIjoxNzE3MDUyMTIyfQ.8TyN57MJ1q_pwib3eHnRiliqgmGf37Oxomizfru9sIcECwN9livRggaHfSpMSipKmo7uWqPNYgssxU9WjSBwjA
