###
GET http://localhost:8001/admin/notices
Access-Token: Bearer eyJkYXRlIjoxNzE3MjA2MzcwODMxLCJ0eXBlIjoiand0IiwiYWxnIjoiSFM1MTIifQ.eyJtZW1iZXJJZCI6InVzZXIwMSIsIm1lbWJlclJvbGUiOiJST0xFX0FETUlOIiwiZXhwIjoxNzE3MjA5OTcwfQ.KbUxu0sOR0Cm_DC-k0FCN0JyNw4IICr5ioirdGu2SwO-RwNa_41J4EF8Dm93SzX3LgKHjwGJhHtsF7v-5JZMLw
###
GET http://localhost:8001/admin/notices/1
Access-Token: Bearer eyJkYXRlIjoxNzE2OTc5MzkxNTE0LCJ0eXBlIjoiand0IiwiYWxnIjoiSFM1MTIifQ.eyJtZW1iZXJSb2xlIjoiUk9MRV9BRE1JTiIsIm1lbWJlcklkIjoidXNlcjAyIiwiZXhwIjoxNzE2OTgyOTkxfQ.aW-B29TmHiKuiCDyDBbi6yNgTgpiu8QisIbFdFUwJcZmdOdTyCEw7rkcppVAqbvzphPINtuFAL8-fWeYbN7reg


###
POST http://localhost:8001/admin/notices
Access-Token: Bearer eyJkYXRlIjoxNzE3MTI3ODgzNjU0LCJ0eXBlIjoiand0IiwiYWxnIjoiSFM1MTIifQ.eyJtZW1iZXJJZCI6InVzZXIwMSIsIm1lbWJlclJvbGUiOiJST0xFX0FETUlOIiwiZXhwIjoxNzE3MTMxNDgzfQ.nTgmm8Bp3uDnEn0ZTpVIlEmAYXABYXFXLuaVIqnBqpmbl7w0YYnKuqrp2uSxbOHKZbl6Q4ES5I5GubwW3JZXDQ
Content-Type: application/json

{
  "noticeTitle" : "등록3",
  "noticeContent" : "내용등록3",
  "noticeFixable" : "N"
}


###
PUT http://localhost:8001/admin/adminNotices/1
Access-Token: Bearer eyJkYXRlIjoxNzE2OTc5MzkxNTE0LCJ0eXBlIjoiand0IiwiYWxnIjoiSFM1MTIifQ.eyJtZW1iZXJSb2xlIjoiUk9MRV9BRE1JTiIsIm1lbWJlcklkIjoidXNlcjAyIiwiZXhwIjoxNzE2OTgyOTkxfQ.aW-B29TmHiKuiCDyDBbi6yNgTgpiu8QisIbFdFUwJcZmdOdTyCEw7rkcppVAqbvzphPINtuFAL8-fWeYbN7reg
Content-Type: application/json

{
  "noticeTitle" : "제목제목11111",
  "noticeContent" : "내용1222"
}

###
DELETE http://localhost:8001/admin/adminNotices/1
Access-Token: Bearer eyJkYXRlIjoxNzE2OTc5MzkxNTE0LCJ0eXBlIjoiand0IiwiYWxnIjoiSFM1MTIifQ.eyJtZW1iZXJSb2xlIjoiUk9MRV9BRE1JTiIsIm1lbWJlcklkIjoidXNlcjAyIiwiZXhwIjoxNzE2OTgyOTkxfQ.aW-B29TmHiKuiCDyDBbi6yNgTgpiu8QisIbFdFUwJcZmdOdTyCEw7rkcppVAqbvzphPINtuFAL8-fWeYbN7reg

###
