###member-inquiry-test

GET http://localhost:8001/inquiry/me?page=1
Access-Token: Bearer eyJkYXRlIjoxNzE2OTYzOTA3MzUyLCJ0eXBlIjoiand0IiwiYWxnIjoiSFM1MTIifQ.eyJtZW1iZXJJZCI6InVzZXIwMiIsIm1lbWJlclJvbGUiOiJST0xFX01FTUJFUiIsImV4cCI6MTcxNjk2NzUwN30.OfUDfItyv6oa4o4lZjXkflFXZDbmFd250jNFFWDsw8pY3iK_ocnXf8EQ7yq4MpbYslHuppWmRWdiv53vKQZ0bA


###member-regist-test
GET http://localhost:8001/inquiry/me/regist
Access-Token: Bearer eyJkYXRlIjoxNzE2OTcxOTUyNDI3LCJ0eXBlIjoiand0IiwiYWxnIjoiSFM1MTIifQ.eyJtZW1iZXJSb2xlIjoiUk9MRV9NRU1CRVIiLCJtZW1iZXJJZCI6InVzZXIwMiIsImV4cCI6MTcxNjk3NTU1Mn0.bZRVwLGx_H9PG_sMOUrdamppNVou3ruc4DbulNkXJ-1XwLAH2jz3Zv9WQ8mLzI3xa7dRMVH9KPz_dTEO1gGFpg


###member-inquiryUpdateList-test
GET http://localhost:8001/inquiry/me/update
Access-Token: Bearer eyJkYXRlIjoxNzE2OTcxOTUyNDI3LCJ0eXBlIjoiand0IiwiYWxnIjoiSFM1MTIifQ.eyJtZW1iZXJSb2xlIjoiUk9MRV9NRU1CRVIiLCJtZW1iZXJJZCI6InVzZXIwMiIsImV4cCI6MTcxNjk3NTU1Mn0.bZRVwLGx_H9PG_sMOUrdamppNVou3ruc4DbulNkXJ-1XwLAH2jz3Zv9WQ8mLzI3xa7dRMVH9KPz_dTEO1gGFpg

