### 회원가입
POST http://localhost:8001/members/signup
Content-Type: application/json

{
  "memberId" : "user02",
  "memberPassword" : "pass02",
  "memberName": "유저2",
  "memberEmail": "user02.greenfire.com",
  "memberPhone": "01012341234",
  "addressSido": "서울시",
  "addressSigungu": "영등포구",
  "addressDongeupmyeon": "양평동",
  "addressDetail": "어딘가",
  "addressZipcode": "12345"
}

### 로그인 테스트
POST http://localhost:8001/members/login
Content-Type: application/json

{
  "memberId" : "user02",
  "memberPassword" : "pass02"
}
