### 주문 등록
POST http://localhost:8001/orders
Content-Type: application/json
Access-Token: Bearer eyJkYXRlIjoxNzE3OTgzODU0NjQ5LCJ0eXBlIjoiand0IiwiYWxnIjoiSFM1MTIifQ.eyJtZW1iZXJJZCI6IjEyMyIsIm1lbWJlclJvbGUiOiJST0xFX01FTUJFUiIsImV4cCI6MTcxNzk4NzQ1NH0.wAa8EeMkw1jIkSUdaL9kZf_TBCn-2GZqy-J8N6EsWKio_h58WPZ0CeCSEKGV317Jo6kM0IX5hNTTWUqrRjK6Fg

{
    "deliveryAddressCode": 1,
    "storeOrders": [
        {
            "orderDetails": [
                {
                    "optionCode": 5,
                    "orderQuantity": 1
                }
            ]
        },
        {
            "orderDetails": [
                {
                    "optionCode": 6,
                    "orderQuantity": 1
                }
            ]
        }
    ]
}

### 주문 승인, 거절
POST http://localhost:8001/orders/apply
Content-Type: application/json
Access-Token: Bearer eyJkYXRlIjoxNzE4MDAxNDgzMTIzLCJ0eXBlIjoiand0IiwiYWxnIjoiSFM1MTIifQ.eyJtZW1iZXJSb2xlIjoiUk9MRV9TRUxMRVIiLCJtZW1iZXJJZCI6IjEyMyIsImV4cCI6MTcxODAwNTA4M30.bRRGWR6hxPeDQq5Rq-oft0ulFbUKTaue2MinipCfgWTrsyFNEB3mfMUzwAabzSW1kMuhqqUGUsl1nULMs_faIw

{
  "orderCode":26,
  "storeCode":8,
  "orderStatus":"주문 거절",
  "rejectionReason": "거절이다"
}


### 회원 주문 조회
GET http://localhost:8001/members/123/orders?page=1
Access-Token: Bearer eyJkYXRlIjoxNzE3OTgzODU0NjQ5LCJ0eXBlIjoiand0IiwiYWxnIjoiSFM1MTIifQ.eyJtZW1iZXJJZCI6IjEyMyIsIm1lbWJlclJvbGUiOiJST0xFX01FTUJFUiIsImV4cCI6MTcxNzk4NzQ1NH0.wAa8EeMkw1jIkSUdaL9kZf_TBCn-2GZqy-J8N6EsWKio_h58WPZ0CeCSEKGV317Jo6kM0IX5hNTTWUqrRjK6Fg
### 회원 주문 상세 조회
GET http://localhost:8001/members/21sol/orders/10
Access-Token: Bearer  eyJkYXRlIjoxNzE3OTA4ODg1NDcwLCJ0eXBlIjoiand0IiwiYWxnIjoiSFM1MTIifQ.eyJtZW1iZXJSb2xlIjoiUk9MRV9NRU1CRVIiLCJtZW1iZXJJZCI6IjIxc29sIiwiZXhwIjoxNzE3OTEyNDg1fQ.GHUOcf8IR3gIXhxkVqIfz62R1DYoPZ4c559kJy0RugTnrhTlGioNUIIchXzBIGipH_t4l0QQ8Ppm2Kyo9Qbv4A