### seller-chl-regist-test
POST http://localhost:8001/seller/challenge/regist
Content-Type: 'application/json'
Access-Token: eyJkYXRlIjoxNzE3MTI3NjQ5NzA3LCJ0eXBlIjoiand0IiwiYWxnIjoiSFM1MTIifQ.eyJtZW1iZXJSb2xlIjoiUk9MRV9NRU1CRVIiLCJtZW1iZXJJZCI6InVzZXIwMyIsImV4cCI6MTcxNzEzMTI0OX0.a6hVAfpu4i-le1nj_mo0iGsHrvCTpkQPXu7DDvpI9T86RTr9F8buLTFoRVCMdLWeMLUpvQKFf98-xmwaVXKRuw

###seller-chl-view-test
GET http://localhost:8001/seller/challenge
Content-Type: 'application/json'
Access-Token: eyJkYXRlIjoxNzE3MTI3NjQ5NzA3LCJ0eXBlIjoiand0IiwiYWxnIjoiSFM1MTIifQ.eyJtZW1iZXJSb2xlIjoiUk9MRV9NRU1CRVIiLCJtZW1iZXJJZCI6InVzZXIwMyIsImV4cCI6MTcxNzEzMTI0OX0.a6hVAfpu4i-le1nj_mo0iGsHrvCTpkQPXu7DDvpI9T86RTr9F8buLTFoRVCMdLWeMLUpvQKFf98-xmwaVXKRuw

### 판매자 보유 스토어 목록 조회 테스트
GET http://localhost:8001/seller/mystore/list/11
Content-Type: 'application/json'
Access-Token: Bearer eyJkYXRlIjoxNzE3MzkzNjIwNDgyLCJ0eXBlIjoiand0IiwiYWxnIjoiSFM1MTIifQ.eyJtZW1iZXJSb2xlIjoiUk9MRV9TRUxMRVIiLCJtZW1iZXJJZCI6InVzZXIwMyIsImV4cCI6MTcxNzM5NzIyMH0.DEBWylDxF2zJG5ymmTQypPgxP27MR7GR0zjmiJnLPnAbgTE8yvkuiOFKrhX003kTpW458Z11M17KayyeTzCiGg

### 스토어 프로필 조회 테스트
GET http://localhost:8001/seller/mystore/10
Content-Type: 'application/json'
Access-Token: Bearer eyJkYXRlIjoxNzE4MjQ1NjQ3MDk3LCJ0eXBlIjoiand0IiwiYWxnIjoiSFM1MTIifQ.eyJtZW1iZXJJZCI6IjEyMyIsIm1lbWJlclJvbGUiOiJST0xFX1NFTExFUiIsImV4cCI6MTcxODI0OTI0N30.QaCI2eg_FNH9sUd6kniC9gnHzptMNOr8IT0MM_IgYF7jr0e8ZlM5KxU6Q9MVyjK1qxKUPagsXgd3N_tZdj07DA

### 스토어 주문 목록 조회 테스트
GET http://localhost:8001/stores/8/orders?page=1
Content-Type: 'application/json'
Access-Token: Bearer eyJkYXRlIjoxNzE4MjQ3MjExMTIyLCJ0eXBlIjoiand0IiwiYWxnIjoiSFM1MTIifQ.eyJtZW1iZXJJZCI6IjEyIiwibWVtYmVyUm9sZSI6IlJPTEVfU0VMTEVSIiwiZXhwIjoxNzE4MjUwODExfQ.Dd0hKH4brqA4HcXmAoaKi9r4kWfEvf0KWr27fUJGIzLNHAJmM-y_Nmo-wtrrRtxhrMQHek4EMPtV7K-rUlUlfw

### 스토어 & 주문 상태에 따른 - 주문 조회목록 조회 테스트
GET http://localhost:8001/stores/8/orders?orderStatus=상품 준비
Content-Type: 'application/json'
Access-Token: Bearer eyJkYXRlIjoxNzE4MjQ3MjExMTIyLCJ0eXBlIjoiand0IiwiYWxnIjoiSFM1MTIifQ.eyJtZW1iZXJJZCI6IjEyIiwibWVtYmVyUm9sZSI6IlJPTEVfU0VMTEVSIiwiZXhwIjoxNzE4MjUwODExfQ.Dd0hKH4brqA4HcXmAoaKi9r4kWfEvf0KWr27fUJGIzLNHAJmM-y_Nmo-wtrrRtxhrMQHek4EMPtV7K-rUlUlfw
