### admin-inquiry-veiw-test
GET http://localhost:8001/admin/inquiry
Access-Token: Bearer eyJkYXRlIjoxNzE3MDQ5NjQwOTI3LCJ0eXBlIjoiand0IiwiYWxnIjoiSFM1MTIifQ.eyJtZW1iZXJJZCI6InVzZXIwMiIsIm1lbWJlclJvbGUiOiJST0xFX0FETUlOIiwiZXhwIjoxNzE3MDUzMjQwfQ.UjfzDsbe9TI29myRCWLGI77a_sae6K7V3vpUCQzUZP1JDkqcvxWwnS6_YeCwnidAGm8NVkTq_Hh7P9HUjQDcDw

###admin-inquiry-regist-test
GET http://localhost:8001/admin/inquiry/regist
Access-Token: Bearer eyJkYXRlIjoxNzE3MDQ5NjQwOTI3LCJ0eXBlIjoiand0IiwiYWxnIjoiSFM1MTIifQ.eyJtZW1iZXJJZCI6InVzZXIwMiIsIm1lbWJlclJvbGUiOiJST0xFX0FETUlOIiwiZXhwIjoxNzE3MDUzMjQwfQ.UjfzDsbe9TI29myRCWLGI77a_sae6K7V3vpUCQzUZP1JDkqcvxWwnS6_YeCwnidAGm8NVkTq_Hh7P9HUjQDcDw


###admin-inquiry-rmove-test
GET http://localhost:8001/admin/inquiry/rm
Access-Token: Bearer eyJkYXRlIjoxNzE3MDQ5NjQwOTI3LCJ0eXBlIjoiand0IiwiYWxnIjoiSFM1MTIifQ.eyJtZW1iZXJJZCI6InVzZXIwMiIsIm1lbWJlclJvbGUiOiJST0xFX0FETUlOIiwiZXhwIjoxNzE3MDUzMjQwfQ.UjfzDsbe9TI29myRCWLGI77a_sae6K7V3vpUCQzUZP1JDkqcvxWwnS6_YeCwnidAGm8NVkTq_Hh7P9HUjQDcDw
