###member-inquiry-test

GET http://localhost:8001/inquiry/member/list?page=1
Access-Token: Bearer eyJkYXRlIjoxNzE3NDkwNzY0MjMwLCJ0eXBlIjoiand0IiwiYWxnIjoiSFM1MTIifQ.eyJtZW1iZXJJZCI6InVzZXIwMiIsIm1lbWJlclJvbGUiOiJST0xFX01FTUJFUiIsImV4cCI6MTcxNzQ5NDM2NH0.0XZFFWs_-IVuo_baRJcnZ6OpwjTDJxs2ZfPzma5-1r_rODGlSAqf4k3Jn4elNHNgwiqyDvbvCeUDpO2N9EFuuQ


###member-regist-test
POST http://localhost:8001/inquiry/member/regist
Access-Token: Bearer eyJkYXRlIjoxNzE3NDkxODEwMjMxLCJ0eXBlIjoiand0IiwiYWxnIjoiSFM1MTIifQ.eyJtZW1iZXJJZCI6InVzZXIwMiIsIm1lbWJlclJvbGUiOiJST0xFX01FTUJFUiIsImV4cCI6MTcxNzQ5NTQxMH0.OERBDBaGPfJ_xSrMiLwKvmfrTu_ERuZ7nFOb71Fait-wlZJtMwFhj1gk-b09b3vXNCfZrSB4B2_hD2TK2DBIbQ

GET http://localhost:8001/inquiry/member/regist
Access-Token: Barer eyJkYXRlIjoxNzE3NTU1ODE1ODI5LCJ0eXBlIjoiand0IiwiYWxnIjoiSFM1MTIifQ.eyJtZW1iZXJJZCI6InVzZXIwMiIsIm1lbWJlclJvbGUiOiJST0xFX01FTUJFUiIsImV4cCI6MTcxNzU1OTQxNX0.t6Hcc6e99HaQnIJTgMco8Osm33DrTFopX52YN6rqsd1EWc0dE-WBcVhVVIY0ewtDypUYvOwfcunzq3W0pZ3vNQ

###member-inquiryUpdateList-test
GET http://localhost:8001/inquiry/me/update
Access-Token: Bearer eyJkYXRlIjoxNzE2OTcxOTUyNDI3LCJ0eXBlIjoiand0IiwiYWxnIjoiSFM1MTIifQ.eyJtZW1iZXJSb2xlIjoiUk9MRV9NRU1CRVIiLCJtZW1iZXJJZCI6InVzZXIwMiIsImV4cCI6MTcxNjk3NTU1Mn0.bZRVwLGx_H9PG_sMOUrdamppNVou3ruc4DbulNkXJ-1XwLAH2jz3Zv9WQ8mLzI3xa7dRMVH9KPz_dTEO1gGFpg

